// Shared custom sort order for John brand categories
// Categories not listed will appear alphabetically at the end

const JOHN_CATEGORY_SORT_ORDER = {
  sheets: [
    'Ravensburger',
    'Μπάλες',
    'John Fun Items',
    'John Καλοκαιρινά',
    'John Fun Items_2',
    'John Παιχνίδια',
    'Πλαστελίνες Paw Patrol',
    'Make Up',
    'Offers',
    'TV',
  ],
  generalCategories: {
    Ravensburger: [
      'CreArt',
      'Κατασκευές',
      '3D Puzzles',
      'Παιδικά Puzzles',
      'Promo Puzzles',
      'Puzzles Ενηλίκων',
      'Αξεσουάρ Puzzle',
      'Επιτραπέζια',
    ],
    'John Fun Items': ['John Fun Items'],
    'John Fun Items_2': ['John Fun Items'],
    'John Καλοκαιρινά': ['John Καλοκαιρινά'],
    'John Παιχνίδια': ['John Παιχνίδια'],
    'Make Up': ['Make Up'],
    Offers: ['John'],
    TV: ['3D Puzzles', 'John Παιχνίδια', 'ΕΠΙΤΡΑΠΕΖΙΑ'],
    Μπάλες: ['Μπάλες'],
    'Πλαστελίνες Paw Patrol': ['Πλαστελίνες Paw Patrol'],
  },
  subCategories: {
    '3D Puzzles': [
      'Οχήματα',
      'Minis',
      'Midi',
      '3d Iconics',
      '3d Special Edition',
      '3D Puzzle Υδρόγειος (NonTV)',
      '3D Puzzle Υδρόγειος',
      '3D NIGHTLIGHT 72 TMX - ΝΈΟ',
      '3D PUZZLEBALLS 72 TMX',
    ],
    CreArt: ['CreArt Canvas', 'CreArt Junior 5+'],
    John: [
      'Καλοκαιρινά',
      'Εκπαιδευτικά Bebe',
      'Fun Items',
      'Σκηνές',
      'Outdoor',
      'Wader',
      'TAIYO',
    ],
    'John Fun Items': ['Νεροπίστολα', 'Ρακέτες & Catchball'],
    'John Fun Items_2': [
      'Σαπουνόφουσκες',
      'Παιχνίδια νερού με κρίκους',
      'Fun Items',
      'Κιμωλίες',
    ],
    'John Καλοκαιρινά': [
      'Μεσσαία κουβαδάκια με αξεσουάρ',
      'Μεγάλα Κουβαδάκια με αξεσουάρ',
      'Κουβαδάκι Κάστρο',
      'Ανώνυμα Κουβαδάκια',
      'Τσαντάκι με σετ παραλίας',
      'Σανίδες 43,5 cm',
      'Σανίδες 82 εκατ.',
      'Ζώνη Πλεύσης',
    ],
    'John Παιχνίδια': [
      'Κούνιες',
      'Σκηνές Pop Up σε κουτί',
      'Επώνυμοι Υπνόσακοι',
      'Επώνυμες Σκηνές',
      'Role Play',
      'Sports',
      'Bowling Sets',
      'Τρεχαλίτσες',
    ],
    'Make Up': ['Πριγίπισσες Disney', 'Frozen', 'Minnie', 'Hello Kitty', 'Stand'],
    'Promo Puzzles': [
      'Παζλ 4 σε 1',
      'Παζλ 4 X 100',
      'Promo Puzzles 25-36-29 τμχ & 48 κάρτες Memory',
    ],
    'Puzzles Ενηλίκων': [
      'Puzzle Moments - NEO',
      'Free Well & Puzzle',
      'Anime',
      'Netflix New',
      'Kidult',
      'Παζλ 500 τεμαχίων',
      'Παζλ 1000 τεμαχίων',
      'Παζλ 1000 τεμαχίων Art Collection',
      'Παζλ 1500 τεμαχίων',
      'Παζλ 2000 τεμαχίων',
      'Παζλ 3000 τεμαχίων',
      'Παζλ 4000 τεμαχίων',
      'Παζλ 5000 τεμαχίων',
      'Παζλ 7000 τεμαχίων',
      'Παζλ 9000 τεμαχίων',
      'Παζλ 18000 τεμαχίων',
      'Παζλ 40000 τεμαχίων',
    ],
    'Αξεσουάρ Puzzle': ['Αξεσουάρ'],
    Επιτραπέζια: [
      'GraviTrax',
      'Bring along games',
      'Memory',
      'Colorino - NEO',
      'Οικογενειακά Επιτραπέζια',
      'Παιχνίδια Καρτών',
      'ThinkFun Παιχνίδια Λογικής',
    ],
    Κατασκευές: ['Art & Crafts New'],
    Μπάλες: [
      'Μπάλες επώνυμες 230 mm',
      'Μπάλες επώνυμες 130 mm',
      '8.5" Rainbow & Neon Sport Balls',
      'PU & High Bounce Balls',
      'Επώνυμα Light Up & Soft Balls',
      'Μικρές Αθλητικές Μπάλες',
      'Επώνυμες Μπάλες Χοπ - Χοπ',
      'Μπάλες ποδοσφαίρου',
      'Μπάλες Βολλευ Soft Grip',
      'Μπάλες Neopren Βόλλευ',
      'Μπάλες Βόλεϋ & Ποδοσφαίρου Neopren',
      'Μπάλες Μπάσκετ',
      'Stand & POS',
    ],
    'Πλαστελίνες Paw Patrol': ['Πλαστελίνες Paw Patrol'],
    'Παιδικά Puzzles': [
      'Παζλ 2/3/4/5τεμ.',
      'Παζλ 6/8/10/12τεμ.',
      'Παζλ Δαπέδου 16 τεμαχίων',
      'Παζλ Δαπέδου 24 τεμαχίων',
      'Παζλ Καρτέλες 15 τεμαχίων',
      'Παζλ Καρτέλες 30-48 τεμαχίων',
      'Παζλ 2x12 τεμαχίων',
      'Παζλ 2x24 τεμαχίων',
      'Παζλ 3x49 τεμαχίων',
      'Παζλ 100XXL τεμαχίων',
      'Παζλ 150XXL τεμαχίων',
      'Παζλ 200XXL τεμαχίων',
      'Παζλ 300XXL τεμαχίων',
    ],
  },
};

export default JOHN_CATEGORY_SORT_ORDER;
